import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/Components/custom_layout_file/custom_layout";
import { child } from "firebase/database";
import CustomLayout from "@/Components/custom_layout_file/custom_layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{{ children }}</body>
    </html>
  );
}
